# Site settings
title: Yixia's Blog
header-img: img/home-bg.jpg
email: yixia.cai@gmail.com
copyright_name: yixia
description: "This is a Yixia's personal blog"
baseurl: ""
url: "http://yixiacai.com"
twitter_username: yixia
github_username:  yixiacai
facebook_username: yixiacai
email_username:  yixia.cai@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
